### ISSUE TITLE
Memory Limit: Investigate

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/govinor#3]
We may need to bump memory limits

See: https://govinor.com/deployments/6901

```
yarn run v1.22.19
$ strapi build && npm run build:addons
Building your admin UI with production configuration...
ℹ Compiling Webpack
[91mKilled
[0m
[91merror Command failed with exit code 137.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1 error occurred:
	* Status: The command '/bin/sh -c NODE_ENV=production yarn build' returned a non-zero code: 137, Code: 137
```

Exit code 137 is OOM

**Comment by dhmacs** [comment]
I've also spotted that we have another problem. Each deployments now takes up much more space due to the git history. I'm looking into optimizing the clone command of govinor

**Comment by danielbeardsley** [comment]
I think if we changed to govinor being activated by a GH action, it'd be easy to have a ~7day timeout where govinor will kill strapi instances that have been around that long and thus free up memory spent on instances that likely won't be used.

**Comment by dhmacs** [comment]
I've deployed a change to Govinor that makes it deploy only on open PR, so this should greatly reduce the number of deployments. Let's see if this is sufficient. If it's not, I'll reopen this and implement the 7 day timeout solution mentioned by @danielbeardsley

**Comment by masonmcelvain** [comment]
We started getting 137's again today, so I'm going to reopen this.

![image](https://github.com/iFixit/govinor/assets/52104630/3673e02c-db0f-47c3-b4ae-f87cf083ca6f)

```
$ strapi build && npm run build:addons
Building your admin UI with production configuration...
[91mBrowserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
[0m
ℹ Compiling Webpack
[91mKilled
[0m
[91merror Command failed with exit code 137.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1 error occurred:
	* Status: The command '/bin/sh -c NODE_ENV=production yarn build' returned a non-zero code: 137, Code: 137

```

**Comment by dhmacs** [comment]
It seems that at times lots of PRs are updated or opened, but the vast majority wouldn't require a Strapi preview instance. When we run out of memory certain instances are not correctly wiped out and that leaves us with zombie deployments.

I see two possible solutions:

1. Deploy a beefier machine capable of handling 50+ concurrent instances (each branch usually takes ~250Mb, so this means a machine with 12.5+ Gb of RAM)
2. Make deployment strategy more efficient by only deploying when there are changes to the `/apps` folder, so we avoid consuming resources for PRs that won't require a Strapi instance

**Comment by masonmcelvain** [comment]
> Make deployment strategy more efficient by only deploying when there are changes to the /apps folder, so we avoid consuming resources for PRs that won't require a Strapi instance

We only generate Vercel previews when there are changes to `/apps` ([ref](https://github.com/iFixit/ifixit/blob/ddc43f9e7e9376714be71206745e74af7980d830/.github/workflows/deploy-nextjs.yml#L7-L8)), so I think that only deploying a Strapi instance if there are changes to `/apps` is a reasonable approach.

**Comment by jarstelfox** [comment]
> We only generate Vercel previews when there are changes to `/apps` ([ref](https://github.com/iFixit/ifixit/blob/ddc43f9e7e9376714be71206745e74af7980d830/.github/workflows/deploy-nextjs.yml#L7-L8)), so I think that only deploying a Strapi instance if there are changes to `/apps` is a reasonable approach.

I think that *may* be misguided in the long run. If we move things into a `/packages` dir and `/apps` uses them we need to be careful and build/deploy the next app if a package changes.

**Comment by masonmcelvain** [comment]
Oh I didn't realize that was being considered. In that case, we'd want to check `/apps` and `/packages` for changes. But I still think that we don't need a Strapi or a Vercel deployment for every pull that makes changes to our PHP app or other unrelated services.

**Comment by danielbeardsley** [comment]
> I think that _may_ be misguided in the long run. If we move things into a `/packages` dir and `/apps` uses them we need to be careful and build/deploy the next app if a package changes.

That's a lot of if's. Also, misguided is a bit strong. Given that we'll already have this problem (vercel preview deploys don't happen when you only edit code outside of `/apps`), then we'll already have to adjust something.

I'm fine with this change. The *worst* case seems to be that we move to `/packages` and we later realize vercel builds don't happen when editing `/packages` only. No harm done, and we can adjust the filter here to include that dir once it becomes a dir we care about.

A possibly lighter weight solution is to have a change to *any* branch setup the proxy rules so that `branchname.govinor.com` proxies to `master.govinor.com`. If the `/apps/strapi` dir is changed, then boot a strapi and replace those rules to proxy to the booted strapi.

**Comment by dhmacs** [comment]
> A possibly lighter weight solution is to have a change to any branch setup the proxy rules so that branchname.govinor.com proxies to master.govinor.com. If the /apps/strapi dir is changed, then boot a strapi and replace those rules to proxy to the booted strapi.

This is a cool idea! It requires a bit more work on Govinor so for now I've shipped the simpler version that detects if a PR has changes in the `apps` folder. 
Let's see how it goes. I'm gonna re-open this if it proves insufficient
