### ISSUE TITLE
Deploy Tags: Ignore them

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/govinor#4]
Deploy tags are listed though always fail (we should ignore tags)

![image](https://github.com/iFixit/govinor/assets/857362/e5dda331-57fd-48a8-b09f-e12730cb340b)
https://govinor.com/deployments/6902

```
Creating deployment assets for branch "refs/tags/deploy-2024-02-12--13-39-04".
Using deploy key to clone repo...
Cloning into 'refs-tags-deploy-2024-02-12--13-39-04'...
fatal: Remote branch refs/tags/deploy-2024-02-12--13-39-04 not found in upstream origin
```

**Comment by dhmacs** [comment]
I've deployed a change that should have fixed this
